# Generated by Django 5.0.4 on 2024-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutResume',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='project_c',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='work_year',
            new_name='edu_year',
        ),
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(upload_to='about'),
        ),
        migrations.AlterField(
            model_name='about',
            name='date_ofb',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about'),
        ),
        migrations.AlterField(
            model_name='about',
            name='zip_code',
            field=models.CharField(max_length=212),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
